resolver: lts-8.14
extra-deps:
- llvm-hs-pure-4.0.0.0
- llvm-hs-4.0.0.0
- encode-string-0.1.0.0

packages:
- '.'
- location:
    git:    https://github.com/llvm-hs/llvm-hs.git
    commit: d3b9de05bc7a8ea032fb1d6431e9f604436fed1f
  extra-dep: true
  subdirs:
    - 'llvm-hs'
    - 'llvm-hs-pure'

flags:
  llvm-hs:
    shared-llvm: true
